tools:
    external_code_coverage:
        timeout: 3000  # Timeout in seconds
        runs: 12       # Scrutinizer will wait for code coverage submissions for every TYPO3_BRANCH declared in .travis.yml
    php_cpd: true
    php_pdepend: true
    php_changetracking: true
    sensiolabs_security_checker: true
