language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - travis_retry composer install --dev

script: ./vendor/bin/php-cs-fixer fix .

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover data/logs/tests/coverage-clover.xml
